engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
      - javascript:

ratings:
  paths:
    - "web/pos/helper.py"
    - "web/pos/tests.py"
    - "web/pos/views.py"
    - "web/pos/models.py"
    - "web/pos/admin.py"
    - "web/pos/templates/"


excluded_paths:
- "**/static/**/*"
- "web/pos/migrations/**"
- "web/pos/settings.py"
