language: python
python:
  - 3.6
  - 3.5

# Enable Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r web/requirements.txt
  - pip install flake8

script: 
  - python web/manage.py test
  - flake8
